/*超级管理员菜单*/
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 1);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 2);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 3);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 4);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 5);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 6);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 7);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 8);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 9);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 11);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 12);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (1, 13);
/*管理员菜单*/
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 1);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 2);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 3);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 4);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 5);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 6);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 7);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 8);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 9);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 10);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 11);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 12);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (2, 13);
/*普通会员菜单*/
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (3, 1);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (3, 2);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (3, 4);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (3, 5);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (3, 6);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (3, 7);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (3, 10);
INSERT INTO `PERMISION_MENU_RELATION` (PERID,MENUID)  VALUES (3, 13);