INSERT INTO `USER_LEVEL` ( `LEVELNAME`, `AMOUNT`, `DAYNUM`) VALUES ( '普通会员', 0, 0);
INSERT INTO `USER_LEVEL` ( `LEVELNAME`, `AMOUNT`, `DAYNUM`) VALUES ( '员工骨干', 190.00, 100);
INSERT INTO `USER_LEVEL` ( `LEVELNAME`, `AMOUNT`, `DAYNUM`) VALUES ( '组长', 390.00, 120);
INSERT INTO `USER_LEVEL` ( `LEVELNAME`, `AMOUNT`, `DAYNUM`) VALUES ( '班长', 690.00, 140);
INSERT INTO `USER_LEVEL` ( `LEVELNAME`, `AMOUNT`, `DAYNUM`) VALUES ( '主管', 1090.00, 160);
INSERT INTO `USER_LEVEL` (`LEVELNAME`, `AMOUNT`, `DAYNUM`) VALUES ( '主任', 1590.00, 180);
INSERT INTO `USER_LEVEL` ( `LEVELNAME`, `AMOUNT`, `DAYNUM`) VALUES ( '经理', 2190.00, 200);